architectureType: llm
inputVariableNames:
  - input
metadata: {}
model: gpt-3.5-turbo
modelParameters:
  temperature: 0.7
modelProvider: OpenAI
modelType: api
name: AI assistant
prompt: 
  - {"role": "user", "content": "{{ input }}"}
